version: "3"

services:
  api:
    build:
      context: .
    volumes: 
      - .:/code
    working_dir: /code
    ports: 
      - "8081:5000"
    environment: 
      - FLASK_APP=alch
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=yeah
      - PYTHONDONTWRITEBYTECODE=nah
    depends_on: 
      - mysql
      - redis
    entrypoint: sh -c "python3 -m venv --copies venv && . venv/bin/activate; pip install -r requirements-dev.txt && flask run --host=0.0.0.0"

  mysql:
    image: mysql:5.7
    volumes: 
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./var/data/mysql:/var/lib/mysql
    ports:
      - "3316:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myalch

  redis:
    image: redis:6.0